/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/callRecords.h>
#include <hzchangrong-tmcs-mib/common.h>

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int send_callRecords_trap(const PacketReportCallRecords *pkt)
{
    netsnmp_variable_list *var_list = NULL;
    const oid callRecords_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 0, 9};
    const oid isConnected_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 1, 0};
    const oid businessType_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 2, 0};
    const oid businessId_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 3, 0};
    const oid causeOfRelease_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 4, 0};
    const oid callingNum_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 5, 0};
    const oid calledNum_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 6, 0};
    const oid thirdpartyNum_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 7, 0};
    const oid makeCallTime_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 8, 0};
    const oid callStartTime_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 9, 0};
    const oid callEndTime_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 2, 10, 0};

    u_int incoming_time;
    u_int start_time;
    u_int end_time;
    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              callRecords_oid, sizeof(callRecords_oid));

    incoming_time = (u_int)pkt->incoming_time;
    start_time = (u_int)pkt->start_time;
    end_time = (u_int)pkt->end_time;
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              isConnected_oid, OID_LENGTH(isConnected_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for isConnected */
                              (const void *)&pkt->is_connected, sizeof(pkt->is_connected));
    snmp_varlist_add_variable(&var_list,
                              businessType_oid, OID_LENGTH(businessType_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for businessType */
                              (const void *)&pkt->business_type, sizeof(pkt->business_type));
    snmp_varlist_add_variable(&var_list,
                              businessId_oid, OID_LENGTH(businessId_oid),
                              ASN_OCTET_STR,
                              /* Set an appropriate value for businessId */
                              (const void *)pkt->business_id, sizeof(pkt->business_id));
    snmp_varlist_add_variable(&var_list,
                              causeOfRelease_oid, OID_LENGTH(causeOfRelease_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for causeOfRelease */
                              (const void *)&pkt->cause_of_release, sizeof(pkt->cause_of_release));
    snmp_varlist_add_variable(&var_list,
                              callingNum_oid, OID_LENGTH(callingNum_oid),
                              ASN_OCTET_STR,
                              /* Set an appropriate value for callingNum */
                              (const void *)pkt->calling_num, COPY_LEN(pkt->calling_num, sizeof(pkt->calling_num)));
    snmp_varlist_add_variable(&var_list,
                              calledNum_oid, OID_LENGTH(calledNum_oid),
                              ASN_OCTET_STR,
                              /* Set an appropriate value for calledNum */
                              (const void *)pkt->called_num, COPY_LEN(pkt->called_num, sizeof(pkt->called_num)));
    snmp_varlist_add_variable(&var_list,
                              thirdpartyNum_oid, OID_LENGTH(thirdpartyNum_oid),
                              ASN_OCTET_STR,
                              /* Set an appropriate value for thirdpartyNum */
                              (const void *)pkt->thirdparty_num, COPY_LEN(pkt->thirdparty_num, sizeof(pkt->thirdparty_num)));
    snmp_varlist_add_variable(&var_list,
                              makeCallTime_oid, OID_LENGTH(makeCallTime_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for makeCallTime */
                              (const void *)&incoming_time, sizeof(incoming_time));
    snmp_varlist_add_variable(&var_list,
                              callStartTime_oid, OID_LENGTH(callStartTime_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for callStartTime */
                              (const void *)&start_time, sizeof(start_time));
    snmp_varlist_add_variable(&var_list,
                              callEndTime_oid, OID_LENGTH(callEndTime_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for callEndTime */
                              (const void *)&end_time, sizeof(end_time));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
