/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CALLRECORDS_H
#define CALLRECORDS_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
int send_callRecords_trap(const PacketReportCallRecords *pkt);

#endif /* CALLRECORDS_H */
