/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/cwpEthStatus.h>

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int send_cwpEthStatus_trap(const PacketReportCwpEthStatus *pkt)
{
    netsnmp_variable_list *var_list = NULL;
    const oid cwpEthStatus_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 0, 11};
    const oid cwpNumForEth_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 1, 1, 0};
    const oid ethStatusOfCwp_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 1, 2, 0};
    u_int cwp_num;

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              cwpEthStatus_oid, sizeof(cwpEthStatus_oid));

    cwp_num = pkt->cwp_num + 1;
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              cwpNumForEth_oid, OID_LENGTH(cwpNumForEth_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for cwpNumForEth */
                              (const void *)&cwp_num, sizeof(cwp_num));
    snmp_varlist_add_variable(&var_list,
                              ethStatusOfCwp_oid, OID_LENGTH(ethStatusOfCwp_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for ethStatusOfCwp */
                              (const void *)&pkt->eth_status, sizeof(pkt->eth_status));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
