/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CWPETHSTATUS_H
#define CWPETHSTATUS_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
int send_cwpEthStatus_trap(const PacketReportCwpEthStatus *pkt);

#endif /* CWPETHSTATUS_H */
