/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CWPINFOCHANGE_H
#define CWPINFOCHANGE_H

/* function declarations */
int send_cwpInfoChange_trap(void);

#endif /* CWPINFOCHANGE_H */
