/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/cwpInfoTable.h>
#include <hzchangrong-tmcs-mib/common.h>
#include <hzchangrong-tmcs-mib/net/proto_def.h>

/** Initializes the cwpInfoTable module */
void init_cwpInfoTable(void)
{
    /* here we initialize all the tables we're planning on supporting */
    initialize_table_cwpInfoTable();
}

// #Determine the first / last column names

/** Initialize the cwpInfoTable table by defining its contents and how it's structured */
void initialize_table_cwpInfoTable(void)
{
    const oid cwpInfoTable_oid[] = {1, 3, 6, 1, 4, 1, 826318, 1, 2, 4};
    const size_t cwpInfoTable_oid_len = OID_LENGTH(cwpInfoTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("cwpInfoTable:init", "initializing table cwpInfoTable\n"));

    reg = netsnmp_create_handler_registration(
        "cwpInfoTable", cwpInfoTable_handler,
        cwpInfoTable_oid, cwpInfoTable_oid_len,
        HANDLER_CAN_RONLY);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info,
                                     ASN_UNSIGNED, /* index: cwpNum */
                                     0);
    table_info->min_column = COLUMN_CWPNUM;
    table_info->max_column = COLUMN_ROLESOFCWP;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point = cwpInfoTable_get_first_data_point;
    iinfo->get_next_data_point = cwpInfoTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    /* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct cwpInfoTable_entry
{
    /* Index values */
    u_long cwpNum;

    /* Column values */
    u_long groupNumOfCwp;
    long cwpStatus;
    char userNameOfCwp[CWP_USER_NAME_LEN + 1];
    size_t userNameOfCwp_len;
    char leftPhoneOfCwp[CWP_PHONE_LEN + 1];
    size_t leftPhoneOfCwp_len;
    char rightPhoneOfCwp[CWP_PHONE_LEN + 1];
    size_t rightPhoneOfCwp_len;
    char rolesOfCwp[CWP_ROLES_LEN + 1];
    size_t rolesOfCwp_len;

    /* Illustrate using a simple linked list */
    int valid;
    struct cwpInfoTable_entry *next;
};

struct cwpInfoTable_entry *cwpInfoTable_head;

/* create a new row in the (unsorted) table */
struct cwpInfoTable_entry *cwpInfoTable_createEntry(const PacketGetCwpInfoAck *pkt)
{
    struct cwpInfoTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct cwpInfoTable_entry);
    if (!entry)
        return NULL;

    entry->cwpNum = pkt->cwp_num + 1;
    entry->groupNumOfCwp = pkt->group_num + 1;
    entry->cwpStatus = pkt->status;
    entry->userNameOfCwp_len = COPY_LEN(pkt->user_name, CWP_USER_NAME_LEN);
    entry->leftPhoneOfCwp_len = COPY_LEN(pkt->left_phone, CWP_PHONE_LEN);
    entry->rightPhoneOfCwp_len = COPY_LEN(pkt->right_phone, CWP_PHONE_LEN);
    entry->rolesOfCwp_len = COPY_LEN(pkt->roles, CWP_ROLES_LEN);
#ifdef WIN32
    strncpy_s(entry->userNameOfCwp, sizeof(entry->userNameOfCwp), pkt->user_name, entry->userNameOfCwp_len);
    strncpy_s(entry->leftPhoneOfCwp, sizeof(entry->leftPhoneOfCwp), pkt->left_phone, entry->leftPhoneOfCwp_len);
    strncpy_s(entry->rightPhoneOfCwp, sizeof(entry->rightPhoneOfCwp), pkt->right_phone, entry->rightPhoneOfCwp_len);
    strncpy_s(entry->rolesOfCwp, sizeof(entry->rolesOfCwp), pkt->roles, entry->rolesOfCwp_len);
#else
    strncpy(entry->userNameOfCwp, pkt->user_name, entry->userNameOfCwp_len);
    strncpy(entry->leftPhoneOfCwp, pkt->left_phone, entry->leftPhoneOfCwp_len);
    strncpy(entry->rightPhoneOfCwp, pkt->right_phone, entry->rightPhoneOfCwp_len);
    strncpy(entry->rolesOfCwp, pkt->roles, entry->rolesOfCwp_len);
#endif
    entry->next = cwpInfoTable_head;
    cwpInfoTable_head = entry;
    return entry;
}

/* remove a row from the table */
void cwpInfoTable_removeEntry(struct cwpInfoTable_entry *entry)
{
    struct cwpInfoTable_entry *ptr, *prev;

    if (!entry)
        return; /* Nothing to remove */

    for (ptr = cwpInfoTable_head, prev = NULL;
         ptr != NULL;
         prev = ptr, ptr = ptr->next)
    {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return; /* Can't find it */

    if (prev == NULL)
        cwpInfoTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry); /* XXX - release any other internal resources */
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
cwpInfoTable_get_first_data_point(void **my_loop_context,
                                  void **my_data_context,
                                  netsnmp_variable_list *put_index_data,
                                  netsnmp_iterator_info *mydata)
{
    *my_loop_context = cwpInfoTable_head;
    return cwpInfoTable_get_next_data_point(my_loop_context, my_data_context,
                                            put_index_data, mydata);
}

netsnmp_variable_list *
cwpInfoTable_get_next_data_point(void **my_loop_context,
                                 void **my_data_context,
                                 netsnmp_variable_list *put_index_data,
                                 netsnmp_iterator_info *mydata)
{
    struct cwpInfoTable_entry *entry = (struct cwpInfoTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry)
    {
        snmp_set_var_typed_integer(idx, ASN_UNSIGNED, entry->cwpNum);
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    }
    else
    {
        return NULL;
    }
}

/** handles requests for the cwpInfoTable table */
int cwpInfoTable_handler(
    netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info *reqinfo,
    netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct cwpInfoTable_entry *table_entry;

    DEBUGMSGTL(("cwpInfoTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode)
    {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next)
        {
            table_entry = (struct cwpInfoTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum)
            {
            case COLUMN_CWPNUM:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
                                           table_entry->cwpNum);
                break;
            case COLUMN_GROUPNUMOFCWP:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
                                           table_entry->groupNumOfCwp);
                break;
            case COLUMN_CWPSTATUS:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->cwpStatus);
                break;
            case COLUMN_USERNAMEOFCWP:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->userNameOfCwp,
                                         table_entry->userNameOfCwp_len);
                break;
            case COLUMN_LEFTPHONEOFCWP:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->leftPhoneOfCwp,
                                         table_entry->leftPhoneOfCwp_len);
                break;
            case COLUMN_RIGHTPHONEOFCWP:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->rightPhoneOfCwp,
                                         table_entry->rightPhoneOfCwp_len);
                break;
            case COLUMN_ROLESOFCWP:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->rolesOfCwp,
                                         table_entry->rolesOfCwp_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
