/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef CWPINFOTABLE_H
#define CWPINFOTABLE_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
void init_cwpInfoTable(void);
void initialize_table_cwpInfoTable(void);
Netsnmp_Node_Handler cwpInfoTable_handler;
Netsnmp_First_Data_Point cwpInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point cwpInfoTable_get_next_data_point;

struct cwpInfoTable_entry *cwpInfoTable_createEntry(const PacketGetCwpInfoAck *pkt);
void cwpInfoTable_removeEntry(struct cwpInfoTable_entry *entry);

/* column number definitions for table cwpInfoTable */
#define COLUMN_CWPNUM 1
#define COLUMN_GROUPNUMOFCWP 2
#define COLUMN_CWPSTATUS 3
#define COLUMN_USERNAMEOFCWP 5
#define COLUMN_LEFTPHONEOFCWP 6
#define COLUMN_RIGHTPHONEOFCWP 7
#define COLUMN_ROLESOFCWP 8

#endif /* CWPINFOTABLE_H */
