/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CWPPOWERSTATUS_H
#define CWPPOWERSTATUS_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
int send_cwpPowerStatus_trap(const PacketReportCwpPowerStatus *pkt);

#endif /* CWPPOWERSTATUS_H */
