/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVINFOCHANGE_H
#define DEVINFOCHANGE_H

/* function declarations */
int send_devInfoChange_trap(void);

#endif /* DEVINFOCHANGE_H */
