/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/devInfoTable.h>
#include <hzchangrong-tmcs-mib/common.h>

/** Initializes the devInfoTable module */
void init_devInfoTable(void)
{
    /* here we initialize all the tables we're planning on supporting */
    initialize_table_devInfoTable();
}

// #Determine the first / last column names

/** Initialize the devInfoTable table by defining its contents and how it's structured */
void initialize_table_devInfoTable(void)
{
    const oid devInfoTable_oid[] = {1, 3, 6, 1, 4, 1, 826318, 1, 2, 1};
    const size_t devInfoTable_oid_len = OID_LENGTH(devInfoTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("devInfoTable:init", "initializing table devInfoTable\n"));

    reg = netsnmp_create_handler_registration(
        "devInfoTable", devInfoTable_handler,
        devInfoTable_oid, devInfoTable_oid_len,
        HANDLER_CAN_RONLY);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info,
                                     ASN_UNSIGNED, /* index: devNum */
                                     0);
    table_info->min_column = COLUMN_DEVNUM;
    table_info->max_column = COLUMN_DEVNAME;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point = devInfoTable_get_first_data_point;
    iinfo->get_next_data_point = devInfoTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    /* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct devInfoTable_entry
{
    /* Index values */
    u_long devNum;

    /* Column values */
    long devType;
    char devName[DEV_NAME_LEN + 1];
    size_t devName_len;

    /* Illustrate using a simple linked list */
    int valid;
    struct devInfoTable_entry *next;
};

struct devInfoTable_entry *devInfoTable_head;

/* create a new row in the (unsorted) table */
struct devInfoTable_entry *devInfoTable_createEntry(const PacketGetDevInfoAck *pkt)
{
    struct devInfoTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct devInfoTable_entry);
    if (!entry)
        return NULL;

    entry->devNum = pkt->dev_num + 1;
    entry->devType = pkt->dev_type;
    entry->devName_len = COPY_LEN(pkt->dev_name, DEV_NAME_LEN);
    printf("devName_len: %d\n", entry->devName_len);
#ifdef WIN32
    strncpy_s(entry->devName, sizeof(entry->devName), pkt->dev_name, entry->devName_len);
#else
    strncpy(entry->devName, pkt->dev_name, entry->devName_len + 1);
#endif
    entry->next = devInfoTable_head;
    devInfoTable_head = entry;
    return entry;
}

/* remove a row from the table */
void devInfoTable_removeEntry(struct devInfoTable_entry *entry)
{
    struct devInfoTable_entry *ptr, *prev;

    if (!entry)
        return; /* Nothing to remove */

    for (ptr = devInfoTable_head, prev = NULL;
         ptr != NULL;
         prev = ptr, ptr = ptr->next)
    {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return; /* Can't find it */

    if (prev == NULL)
        devInfoTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry); /* XXX - release any other internal resources */
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
devInfoTable_get_first_data_point(void **my_loop_context,
                                  void **my_data_context,
                                  netsnmp_variable_list *put_index_data,
                                  netsnmp_iterator_info *mydata)
{
    *my_loop_context = devInfoTable_head;
    return devInfoTable_get_next_data_point(my_loop_context, my_data_context,
                                            put_index_data, mydata);
}

netsnmp_variable_list *
devInfoTable_get_next_data_point(void **my_loop_context,
                                 void **my_data_context,
                                 netsnmp_variable_list *put_index_data,
                                 netsnmp_iterator_info *mydata)
{
    struct devInfoTable_entry *entry = (struct devInfoTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry)
    {
        snmp_set_var_typed_integer(idx, ASN_UNSIGNED, entry->devNum);
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    }
    else
    {
        return NULL;
    }
}

/** handles requests for the devInfoTable table */
int devInfoTable_handler(
    netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info *reqinfo,
    netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct devInfoTable_entry *table_entry;

    DEBUGMSGTL(("devInfoTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode)
    {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next)
        {
            table_entry = (struct devInfoTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum)
            {
            case COLUMN_DEVNUM:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
                                           table_entry->devNum);
                break;
            case COLUMN_DEVTYPE:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->devType);
                break;
            case COLUMN_DEVNAME:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->devName,
                                         table_entry->devName_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
