/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef DEVINFOTABLE_H
#define DEVINFOTABLE_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
void init_devInfoTable(void);
void initialize_table_devInfoTable(void);
Netsnmp_Node_Handler devInfoTable_handler;
Netsnmp_First_Data_Point devInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point devInfoTable_get_next_data_point;

struct devInfoTable_entry *devInfoTable_createEntry(const PacketGetDevInfoAck *pkt);
void devInfoTable_removeEntry(struct devInfoTable_entry *entry);

/* column number definitions for table devInfoTable */
#define COLUMN_DEVNUM 1
#define COLUMN_DEVTYPE 2
#define COLUMN_DEVNAME 3

#endif /* DEVINFOTABLE_H */
