/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FUNCBTNINFOS_H
#define FUNCBTNINFOS_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
int send_funcBtnInfos_trap(int cwp_num, const FuncButtonInfo *btn_info);

#endif /* FUNCBTNINFOS_H */
