/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/funcBtnInfos.h>
#include <hzchangrong-tmcs-mib/common.h>

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int send_funcBtnInfos_trap(int cwp_num, const FuncButtonInfo *btn_info)
{
    netsnmp_variable_list *var_list = NULL;
    const oid funcBtnInfos_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 0, 8};
    const oid cwpNumForFunc_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 5, 1, 0};
    const oid funcBtnNum_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 5, 2, 0};
    const oid funcBtnName_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 5, 3, 0};
    const oid funcBtnType_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 5, 4, 0};
    u_int cwp_number;
    u_int btn_num;

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              funcBtnInfos_oid, sizeof(funcBtnInfos_oid));

    cwp_number = cwp_num + 1;
    btn_num = btn_info->btn_num + 1;
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              cwpNumForFunc_oid, OID_LENGTH(cwpNumForFunc_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for cwpNumForFunc */
                              (const void *)&cwp_number, sizeof(cwp_number));
    snmp_varlist_add_variable(&var_list,
                              funcBtnNum_oid, OID_LENGTH(funcBtnNum_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for funcBtnNum */
                              (const void *)&btn_num, sizeof(btn_num));
    snmp_varlist_add_variable(&var_list,
                              funcBtnName_oid, OID_LENGTH(funcBtnName_oid),
                              ASN_OCTET_STR,
                              /* Set an appropriate value for funcBtnName */
                              (const void *)btn_info->name, COPY_LEN(btn_info->name, sizeof(btn_info->name)));
    snmp_varlist_add_variable(&var_list,
                              funcBtnType_oid, OID_LENGTH(funcBtnType_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for funcBtnType */
                              (const void *)&btn_info->type, sizeof(btn_info->type));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
