/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef LIUETHSTATUS_H
#define LIUETHSTATUS_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
int send_liuEthStatus_trap(const PacketReportLiuEthStatus *pkt);

#endif /* LIUETHSTATUS_H */
