/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/liuEthStatus.h>

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int send_liuEthStatus_trap(const PacketReportLiuEthStatus *pkt)
{
    netsnmp_variable_list *var_list = NULL;
    const oid liuEthStatus_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 0, 10};
    const oid lrFlag_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 3, 1, 0};
    const oid devNumOfLiu_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 3, 2, 0};
    const oid eth1StatusOfLiu_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 3, 3, 0};
    const oid eth2StatusOfLiu_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 3, 4, 0};
    u_int dev_num;

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              liuEthStatus_oid, sizeof(liuEthStatus_oid));

    dev_num = pkt->dev_num + 1;
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              lrFlag_oid, OID_LENGTH(lrFlag_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for lrFlag */
                              (const void *)&pkt->lr_flag, sizeof(pkt->lr_flag));
    snmp_varlist_add_variable(&var_list,
                              devNumOfLiu_oid, OID_LENGTH(devNumOfLiu_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for devNumOfLiu */
                              (const void *)&dev_num, sizeof(dev_num));
    snmp_varlist_add_variable(&var_list,
                              eth1StatusOfLiu_oid, OID_LENGTH(eth1StatusOfLiu_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for eth1StatusOfLiu */
                              (const void *)&pkt->eth1_status, sizeof(pkt->eth1_status));
    snmp_varlist_add_variable(&var_list,
                              eth2StatusOfLiu_oid, OID_LENGTH(eth2StatusOfLiu_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for eth2StatusOfLiu */
                              (const void *)&pkt->eth2_status, sizeof(pkt->eth2_status));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
