/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef MPUINFOTABLE_H
#define MPUINFOTABLE_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
void init_mpuInfoTable(void);
void initialize_table_mpuInfoTable(void);
Netsnmp_Node_Handler mpuInfoTable_handler;
Netsnmp_First_Data_Point mpuInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point mpuInfoTable_get_next_data_point;

struct mpuInfoTable_entry *mpuInfoTable_createEntry(const PacketGetMpuInfoAck *pkt);
void mpuInfoTable_removeEntry(struct mpuInfoTable_entry *entry);

/* column number definitions for table mpuInfoTable */
#define COLUMN_DEVNUMOFMPU 1
#define COLUMN_SLOTNUMOFMPU 2
#define COLUMN_MPUSTATUS 3

#endif /* MPUINFOTABLE_H */
