/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef MPUINFOCHANGE_H
#define MPUINFOCHANGE_H

/* function declarations */
int send_mpuInfoChange_trap(void);

#endif /* MPUINFOCHANGE_H */
