/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/mpuInfoTable.h>

/** Initializes the mpuInfoTable module */
void init_mpuInfoTable(void)
{
    /* here we initialize all the tables we're planning on supporting */
    initialize_table_mpuInfoTable();
}

// #Determine the first / last column names

/** Initialize the mpuInfoTable table by defining its contents and how it's structured */
void initialize_table_mpuInfoTable(void)
{
    const oid mpuInfoTable_oid[] = {1, 3, 6, 1, 4, 1, 826318, 1, 2, 2};
    const size_t mpuInfoTable_oid_len = OID_LENGTH(mpuInfoTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("mpuInfoTable:init", "initializing table mpuInfoTable\n"));

    reg = netsnmp_create_handler_registration(
        "mpuInfoTable", mpuInfoTable_handler,
        mpuInfoTable_oid, mpuInfoTable_oid_len,
        HANDLER_CAN_RONLY);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info,
                                     ASN_UNSIGNED, /* index: devNumOfMpu */
                                     ASN_UNSIGNED, /* index: slotNumOfMpu */
                                     0);
    table_info->min_column = COLUMN_DEVNUMOFMPU;
    table_info->max_column = COLUMN_MPUSTATUS;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point = mpuInfoTable_get_first_data_point;
    iinfo->get_next_data_point = mpuInfoTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    /* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct mpuInfoTable_entry
{
    /* Index values */
    u_long devNumOfMpu;
    u_long slotNumOfMpu;

    /* Column values */
    long mpuStatus;

    /* Illustrate using a simple linked list */
    int valid;
    struct mpuInfoTable_entry *next;
};

struct mpuInfoTable_entry *mpuInfoTable_head;

/* create a new row in the (unsorted) table */
struct mpuInfoTable_entry *mpuInfoTable_createEntry(const PacketGetMpuInfoAck *pkt)
{
    struct mpuInfoTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct mpuInfoTable_entry);
    if (!entry)
        return NULL;

    entry->devNumOfMpu = pkt->dev_num + 1;
    entry->slotNumOfMpu = pkt->slot_num + 1;
    entry->mpuStatus = pkt->status;
    entry->next = mpuInfoTable_head;
    mpuInfoTable_head = entry;
    return entry;
}

/* remove a row from the table */
void mpuInfoTable_removeEntry(struct mpuInfoTable_entry *entry)
{
    struct mpuInfoTable_entry *ptr, *prev;

    if (!entry)
        return; /* Nothing to remove */

    for (ptr = mpuInfoTable_head, prev = NULL;
         ptr != NULL;
         prev = ptr, ptr = ptr->next)
    {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return; /* Can't find it */

    if (prev == NULL)
        mpuInfoTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry); /* XXX - release any other internal resources */
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
mpuInfoTable_get_first_data_point(void **my_loop_context,
                                  void **my_data_context,
                                  netsnmp_variable_list *put_index_data,
                                  netsnmp_iterator_info *mydata)
{
    *my_loop_context = mpuInfoTable_head;
    return mpuInfoTable_get_next_data_point(my_loop_context, my_data_context,
                                            put_index_data, mydata);
}

netsnmp_variable_list *
mpuInfoTable_get_next_data_point(void **my_loop_context,
                                 void **my_data_context,
                                 netsnmp_variable_list *put_index_data,
                                 netsnmp_iterator_info *mydata)
{
    struct mpuInfoTable_entry *entry = (struct mpuInfoTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry)
    {
        snmp_set_var_typed_integer(idx, ASN_UNSIGNED, entry->devNumOfMpu);
        idx = idx->next_variable;
        snmp_set_var_typed_integer(idx, ASN_UNSIGNED, entry->slotNumOfMpu);
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    }
    else
    {
        return NULL;
    }
}

/** handles requests for the mpuInfoTable table */
int mpuInfoTable_handler(
    netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info *reqinfo,
    netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct mpuInfoTable_entry *table_entry;

    DEBUGMSGTL(("mpuInfoTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode)
    {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next)
        {
            table_entry = (struct mpuInfoTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum)
            {
            case COLUMN_DEVNUMOFMPU:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
                                           table_entry->devNumOfMpu);
                break;
            case COLUMN_SLOTNUMOFMPU:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
                                           table_entry->slotNumOfMpu);
                break;
            case COLUMN_MPUSTATUS:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->mpuStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
