/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef PHONEBTNINFOS_H
#define PHONEBTNINFOS_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
int send_phoneBtnInfos_trap(int cwp_num, const PhoneButtonInfo *btn_info);

#endif /* PHONEBTNINFOS_H */
