/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef RADIOBTNINFOS_H
#define RADIOBTNINFOS_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
int send_radioBtnInfos_trap(int cwp_num, const RadioButtonInfo *btn_info);

#endif /* RADIOBTNINFOS_H */
