/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/radioBtnInfos.h>
#include <hzchangrong-tmcs-mib/common.h>

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int send_radioBtnInfos_trap(int cwp_num, const RadioButtonInfo *btn_info)
{
    netsnmp_variable_list *var_list = NULL;
    const oid radioBtnInfos_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 0, 7};
    const oid cwpNumForRadio_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 4, 1, 0};
    const oid radioBtnNum_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 4, 2, 0};
    const oid radioBtnName_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 4, 3, 0};
    const oid frequency_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 4, 4, 0};
    const oid lifesaving_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 4, 5, 0};
    const oid isRadioBtnEnable_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 2, 4, 6, 0};
    u_int cwp_number;
    u_int btn_num;

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              radioBtnInfos_oid, sizeof(radioBtnInfos_oid));

    cwp_number = cwp_num + 1;
    btn_num = btn_info->btn_num + 1;
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              cwpNumForRadio_oid, OID_LENGTH(cwpNumForRadio_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for cwpNumForRadio */
                              (const void *)&cwp_number, sizeof(cwp_number));
    snmp_varlist_add_variable(&var_list,
                              radioBtnNum_oid, OID_LENGTH(radioBtnNum_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for radioBtnNum */
                              (const void *)&btn_num, sizeof(btn_num));
    snmp_varlist_add_variable(&var_list,
                              radioBtnName_oid, OID_LENGTH(radioBtnName_oid),
                              ASN_OCTET_STR,
                              /* Set an appropriate value for radioBtnName */
                              (const void *)btn_info->name, COPY_LEN(btn_info->name, sizeof(btn_info->name)));
    snmp_varlist_add_variable(&var_list,
                              frequency_oid, OID_LENGTH(frequency_oid),
                              ASN_OCTET_STR,
                              /* Set an appropriate value for frequency */
                              (const void *)btn_info->frequency, COPY_LEN(btn_info->frequency, sizeof(btn_info->frequency)));
    snmp_varlist_add_variable(&var_list,
                              lifesaving_oid, OID_LENGTH(lifesaving_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for lifesaving */
                              (const void *)&btn_info->lifesaving, sizeof(btn_info->lifesaving));
    snmp_varlist_add_variable(&var_list,
                              isRadioBtnEnable_oid, OID_LENGTH(isRadioBtnEnable_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for isRadioBtnEnable */
                              (const void *)&btn_info->can_use, sizeof(btn_info->can_use));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
