/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/riuInfoTable.h>

/** Initializes the riuInfoTable module */
void init_riuInfoTable(void)
{
    /* here we initialize all the tables we're planning on supporting */
    initialize_table_riuInfoTable();
}

// #Determine the first / last column names

/** Initialize the riuInfoTable table by defining its contents and how it's structured */
void initialize_table_riuInfoTable(void)
{
    const oid riuInfoTable_oid[] = {1, 3, 6, 1, 4, 1, 826318, 1, 2, 3};
    const size_t riuInfoTable_oid_len = OID_LENGTH(riuInfoTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("riuInfoTable:init", "initializing table riuInfoTable\n"));

    reg = netsnmp_create_handler_registration(
        "riuInfoTable", riuInfoTable_handler,
        riuInfoTable_oid, riuInfoTable_oid_len,
        HANDLER_CAN_RONLY);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info,
                                     ASN_UNSIGNED, /* index: frameNumOfRiu */
                                     ASN_UNSIGNED, /* index: slotNumOfRiu */
                                     0);
    table_info->min_column = COLUMN_FRAMENUMOFRIU;
    table_info->max_column = COLUMN_GROUPNUMOFRIU;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point = riuInfoTable_get_first_data_point;
    iinfo->get_next_data_point = riuInfoTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    /* Initialise the contents of the table here */
}

/* Typical data structure for a row entry */
struct riuInfoTable_entry
{
    /* Index values */
    u_long frameNumOfRiu;
    u_long slotNumOfRiu;

    /* Column values */
    long riuStatus;
    long riuType;
    long activeStandby;
    u_long groupNumOfRiu;

    /* Illustrate using a simple linked list */
    int valid;
    struct riuInfoTable_entry *next;
};

struct riuInfoTable_entry *riuInfoTable_head;

/* create a new row in the (unsorted) table */
struct riuInfoTable_entry *riuInfoTable_createEntry(const PacketGetRiuInfoAck *pkt)
{
    struct riuInfoTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct riuInfoTable_entry);
    if (!entry)
        return NULL;

    entry->frameNumOfRiu = pkt->frame_num + 1;
    entry->slotNumOfRiu = pkt->slot_num + 1;
    entry->riuStatus = pkt->status;
    entry->riuType = pkt->type;
    entry->activeStandby = pkt->active_standby;
    entry->groupNumOfRiu = pkt->group_num + 1;
    entry->next = riuInfoTable_head;
    riuInfoTable_head = entry;
    return entry;
}

/* remove a row from the table */
void riuInfoTable_removeEntry(struct riuInfoTable_entry *entry)
{
    struct riuInfoTable_entry *ptr, *prev;

    if (!entry)
        return; /* Nothing to remove */

    for (ptr = riuInfoTable_head, prev = NULL;
         ptr != NULL;
         prev = ptr, ptr = ptr->next)
    {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return; /* Can't find it */

    if (prev == NULL)
        riuInfoTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry); /* XXX - release any other internal resources */
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
riuInfoTable_get_first_data_point(void **my_loop_context,
                                  void **my_data_context,
                                  netsnmp_variable_list *put_index_data,
                                  netsnmp_iterator_info *mydata)
{
    *my_loop_context = riuInfoTable_head;
    return riuInfoTable_get_next_data_point(my_loop_context, my_data_context,
                                            put_index_data, mydata);
}

netsnmp_variable_list *
riuInfoTable_get_next_data_point(void **my_loop_context,
                                 void **my_data_context,
                                 netsnmp_variable_list *put_index_data,
                                 netsnmp_iterator_info *mydata)
{
    struct riuInfoTable_entry *entry = (struct riuInfoTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry)
    {
        snmp_set_var_typed_integer(idx, ASN_UNSIGNED, entry->frameNumOfRiu);
        idx = idx->next_variable;
        snmp_set_var_typed_integer(idx, ASN_UNSIGNED, entry->slotNumOfRiu);
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    }
    else
    {
        return NULL;
    }
}

/** handles requests for the riuInfoTable table */
int riuInfoTable_handler(
    netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info *reqinfo,
    netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct riuInfoTable_entry *table_entry;

    DEBUGMSGTL(("riuInfoTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode)
    {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next)
        {
            table_entry = (struct riuInfoTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum)
            {
            case COLUMN_FRAMENUMOFRIU:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
                                           table_entry->frameNumOfRiu);
                break;
            case COLUMN_SLOTNUMOFRIU:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
                                           table_entry->slotNumOfRiu);
                break;
            case COLUMN_RIUSTATUS:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->riuStatus);
                break;
            case COLUMN_RIUTYPE:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->riuType);
                break;
            case COLUMN_ACTIVESTANDBY:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->activeStandby);
                break;
            case COLUMN_GROUPNUMOFRIU:
                if (!table_entry)
                {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
                                           table_entry->groupNumOfRiu);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
