/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef RIUINFOCHANGE_H
#define RIUINFOCHANGE_H

/* function declarations */
int send_riuInfoChange_trap(void);

#endif /* RIUINFOCHANGE_H */
