/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/riuInfoChange.h>

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int send_riuInfoChange_trap(void)
{
    netsnmp_variable_list *var_list = NULL;
    const oid riuInfoChange_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 0, 3};

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              riuInfoChange_oid, sizeof(riuInfoChange_oid));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
