/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef RIUINFOTABLE_H
#define RIUINFOTABLE_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
void init_riuInfoTable(void);
void initialize_table_riuInfoTable(void);
Netsnmp_Node_Handler riuInfoTable_handler;
Netsnmp_First_Data_Point riuInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point riuInfoTable_get_next_data_point;

struct riuInfoTable_entry *riuInfoTable_createEntry(const PacketGetRiuInfoAck *pkt);
void riuInfoTable_removeEntry(struct riuInfoTable_entry *entry);

/* column number definitions for table riuInfoTable */
#define COLUMN_FRAMENUMOFRIU 1
#define COLUMN_SLOTNUMOFRIU 2
#define COLUMN_RIUSTATUS 3
#define COLUMN_RIUTYPE 4
#define COLUMN_ACTIVESTANDBY 5
#define COLUMN_GROUPNUMOFRIU 6

#endif /* RIUINFOTABLE_H */
