/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef RIUPORTSSTATUS_H
#define RIUPORTSSTATUS_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
int send_riuPortsStatus_trap(const PacketReportRiuPortStatus *pkt);

#endif /* RIUPORTSSTATUS_H */
