/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/riuPortsStatus.h>

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int send_riuPortsStatus_trap(const PacketReportRiuPortStatus *pkt)
{
    netsnmp_variable_list *var_list = NULL;
    const oid riuPortsStatus_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 0, 5};
    const oid portNum_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 1, 1, 0};
    const oid frameNumOfPort_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 1, 2, 0};
    const oid slotNumOfPort_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 1, 3, 0};
    const oid portStatus_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 1, 4, 0};
    const oid portType_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 1, 5, 0};
    u_int port_num;
    u_int frame_num;
    u_int slot_num;

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              riuPortsStatus_oid, sizeof(riuPortsStatus_oid));

    port_num = pkt->port_num + 1;
    frame_num = pkt->frame_num + 1;
    slot_num = pkt->slot_num + 1;
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              portNum_oid, OID_LENGTH(portNum_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for portNum */
                              (const void *)&port_num, sizeof(port_num));
    snmp_varlist_add_variable(&var_list,
                              frameNumOfPort_oid, OID_LENGTH(frameNumOfPort_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for frameNumOfPort */
                              (const void *)&frame_num, sizeof(frame_num));
    snmp_varlist_add_variable(&var_list,
                              slotNumOfPort_oid, OID_LENGTH(slotNumOfPort_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for slotNumOfPort */
                              (const void *)&slot_num, sizeof(slot_num));
    snmp_varlist_add_variable(&var_list,
                              portStatus_oid, OID_LENGTH(portStatus_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for portStatus */
                              (const void *)&pkt->status, sizeof(pkt->status));
    snmp_varlist_add_variable(&var_list,
                              portType_oid, OID_LENGTH(portType_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for portType */
                              (const void *)&pkt->type, sizeof(pkt->type));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
