/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <hzchangrong-tmcs-mib/management/servEthStatus.h>

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int send_servEthStatus_trap(u_int serv_num, int status)
{
    netsnmp_variable_list *var_list = NULL;
    const oid servEthStatus_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 0, 13};
    const oid servNum_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 4, 1, 0};
    const oid servStatus_oid[] = {1, 3, 6, 1, 4, 1, 826318, 2, 2, 1, 4, 2, 0};

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              servEthStatus_oid, sizeof(servEthStatus_oid));

    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              servNum_oid, OID_LENGTH(servNum_oid),
                              ASN_UNSIGNED,
                              /* Set an appropriate value for servNum */
                              (const void *)&serv_num, sizeof(serv_num));
    snmp_varlist_add_variable(&var_list,
                              servStatus_oid, OID_LENGTH(servStatus_oid),
                              ASN_INTEGER,
                              /* Set an appropriate value for servStatus */
                              (const void *)&status, sizeof(status));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
