/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef SERVETHSTATUS_H
#define SERVETHSTATUS_H

#include <hzchangrong-tmcs-mib/net/proto_def.h>

/* function declarations */
int send_servEthStatus_trap(u_int serv_num, int status);

#endif /* SERVETHSTATUS_H */
